apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  type: NodePort 
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: wil-playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
spec:
  selector:
    matchLabels:
      app: wil-playground
  replicas: 1
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: ngnix
        ports:
        - containerPort: 80